apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: poc
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString 
    secretKeyRef:
      name: servicebus-secret
      key: root-connectionString
