apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: poc
spec:
  type: state.azure.blobstorage
  version: v1
  metadata:
  - name: accountName
    value: zygdemo
  - name: accountKey
    secretKeyRef:
      name: storage-secret
      key: accountKey
  - name: containerName
    value: statestore
  - name: azureEnvironment
    value: AZURECHINACLOUD
