name: approval-ci

env:
  PROJECT_NAME: approval

on: 
  workflow_dispatch:
  push:
    branches: 
    - "main"
    paths:
    - "/src/${{ env.PROJECT_NAME }}/**"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Checkout the source code
      uses: actions/checkout@v3
    -
      name: Build the Docker image
      run: docker build . --file ./dockerfiles/${{ env.PROJECT_NAME }}.Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/daprapps-poc-${{ env.PROJECT_NAME }}:${{ github.run_number }}
    -
      name: Push the Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/daprapps-poc-${{ env.PROJECT_NAME }}:${{ github.run_number }}
    -
      name: Replace the token of the deploy file
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: "${"
        tokenSuffix: "}$"
        files: "/deploy/${{ env.PROJECT_NAME }}.yaml"
      env:
        CR_URL: ${{ secrets.DOCKERHUB_USERNAME }}
        IMAGE_TAG: ${{ github.run_number }}
    -
      name: Upload the deploy file to artifact
      uses: actions/upload-artifact@v3
      with:
        name: "${{ env.PROJECT_NAME }}-deploy"
        path: "/deploy/${{ env.PROJECT_NAME }}.yaml"
